background {
    monitor =
    color = rgba(0, 0, 0, 1.0)
}

input-field {
    monitor =
    size = 250, 45
    position = 0, 0
    halign = center
    valign = center

    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true

    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(255, 255, 255, 0.6)
    font_color = rgba(255, 255, 255, 0.8)

    fade_on_empty = false
}
